#!/bin/bash

env CGO_ENABLED=0 GO111MODULE=on go build -buildmode=plugin ./... ; rm src.go
if [ "$?" -ne "0" ] ; then exit 1 ; fi
env CGO_ENABLED=0 GO111MODULE=on go build -v -o ./bin/aurolepicker.so ./src/main/main.go
if [ "$?" -ne "0" ] ; then exit 1 ; else echo "Compiled plugin to bin. Move \"`ls bin`\" into a bots plugin dir to use." ; fi
